/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Consultas;

import Views.Consultas.ConsultarJornadaPanel;
import Views.Consultas.ConsultarJugadorPanel;
import Views.Consultas.ConsultarEquipoPanel;
import java.awt.BorderLayout;

/**
 *
 * @author 1gdaw09
 */
public class ConsultasPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsultasPanel
     */
    public ConsultasPanel() {
        initComponents();
    }

    public void ConsultarEquipoPanel(){
//Visualizacion de paneles     
        ConsultarEquipoPanel c1 = new ConsultarEquipoPanel();
        c1.setSize(991, 578);
        c1.setLocation(0, 0);
        
        PInterfazConsultas.removeAll();
        PInterfazConsultas.add(c1, BorderLayout.CENTER);
        PInterfazConsultas.revalidate();
        PInterfazConsultas.repaint();
    }
    
    public void ConsultarJugadorPanel(){
//Visualizacion de paneles     
        ConsultarJugadorPanel c1 = new ConsultarJugadorPanel();
        c1.setSize(991, 578);
        c1.setLocation(0, 0);
        
        PInterfazConsultas.removeAll();
        PInterfazConsultas.add(c1, BorderLayout.CENTER);
        PInterfazConsultas.revalidate();
        PInterfazConsultas.repaint();
    }
    
    
    public void ConsultarPartidoPanel(){
//Visualizacion de paneles     
        ConsultarJornadaPanel c1 = new ConsultarJornadaPanel();
        c1.setSize(991, 578);
        c1.setLocation(0, 0);
        
        PInterfazConsultas.removeAll();
        PInterfazConsultas.add(c1, BorderLayout.CENTER);
        PInterfazConsultas.revalidate();
        PInterfazConsultas.repaint();
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BConsultasEquipo = new javax.swing.JButton();
        BConsultarPartido = new javax.swing.JButton();
        BConsultasJugador = new javax.swing.JButton();
        PInterfazConsultas = new javax.swing.JPanel();

        BConsultasEquipo.setBackground(new java.awt.Color(255, 255, 255));
        BConsultasEquipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BConsultasEquipo.setText("Consultar Equipo");
        BConsultasEquipo.setBorder(null);
        BConsultasEquipo.setBorderPainted(false);
        BConsultasEquipo.setFocusable(false);
        BConsultasEquipo.setOpaque(false);
        BConsultasEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultasEquipoActionPerformed(evt);
            }
        });

        BConsultarPartido.setBackground(new java.awt.Color(255, 255, 255));
        BConsultarPartido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BConsultarPartido.setText("Consultar Jornada");
        BConsultarPartido.setBorder(null);
        BConsultarPartido.setBorderPainted(false);
        BConsultarPartido.setFocusable(false);
        BConsultarPartido.setOpaque(false);
        BConsultarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarPartidoActionPerformed(evt);
            }
        });

        BConsultasJugador.setBackground(new java.awt.Color(255, 255, 255));
        BConsultasJugador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BConsultasJugador.setText("Consultar Jugador");
        BConsultasJugador.setBorder(null);
        BConsultasJugador.setBorderPainted(false);
        BConsultasJugador.setFocusable(false);
        BConsultasJugador.setOpaque(false);
        BConsultasJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultasJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PInterfazConsultasLayout = new javax.swing.GroupLayout(PInterfazConsultas);
        PInterfazConsultas.setLayout(PInterfazConsultasLayout);
        PInterfazConsultasLayout.setHorizontalGroup(
            PInterfazConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        PInterfazConsultasLayout.setVerticalGroup(
            PInterfazConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BConsultasEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(BConsultasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BConsultarPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(PInterfazConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BConsultasEquipo)
                    .addComponent(BConsultasJugador)
                    .addComponent(BConsultarPartido))
                .addGap(40, 40, 40)
                .addComponent(PInterfazConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BConsultasEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultasEquipoActionPerformed
       // TODO add your handling code here:
//LLamar a la clase       
       ConsultarEquipoPanel();
    }//GEN-LAST:event_BConsultasEquipoActionPerformed

    private void BConsultarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarPartidoActionPerformed
        // TODO add your handling code here:  
//LLamar a la clase         
        ConsultarPartidoPanel();
    }//GEN-LAST:event_BConsultarPartidoActionPerformed

    private void BConsultasJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultasJugadorActionPerformed
        // TODO add your handling code here:
//LLamar a la clase 
        ConsultarJugadorPanel();
    }//GEN-LAST:event_BConsultasJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsultarPartido;
    private javax.swing.JButton BConsultasEquipo;
    private javax.swing.JButton BConsultasJugador;
    private javax.swing.JPanel PInterfazConsultas;
    // End of variables declaration//GEN-END:variables
}
