CREATE PUBLIC SYNONYM dueno
for eqdaw03.DUENNO;

CREATE PUBLIC SYNONYM equipo
for eqdaw03.EQUIPO;

CREATE PUBLIC SYNONYM jornada
for eqdaw03.JORNADA;

CREATE PUBLIC SYNONYM jugador
for eqdaw03.JUGADOR;

CREATE PUBLIC SYNONYM partido
for eqdaw03.PARTIDO;

CREATE PUBLIC SYNONYM usuarios
for eqdaw03.USUARIOS;